- id: '1660470443178'
  alias: Danie leaving Canal Walk
  description: Will trigger when Danie's iPhone leaves Canal Walk zone, and announce
    it over lounge speaker
  trigger:
  - platform: zone
    entity_id: device_tracker.danies_iphone_3_2
    zone: zone.canal_walk
    event: leave
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Hey+Chantel%2C+Danie+has+just+left+Canal+Walk
      media_content_type: provider
    metadata:
      title: Hey Chantel, Danie has just left Canal Walk
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Hey+Chantel%2C+Danie+has+just+left+Canal+Walk
  mode: single
- id: '1660475333188'
  alias: Say it started raining
  description: If hourly rainfall moves above 0 then say it started raining now (only
    when sun above horizon)
  trigger:
  - type: value
    platform: device
    device_id: 678c05c3b91925a60db50c480d33c096
    entity_id: sensor.thornton_hourly_rain_rate
    domain: sensor
    above: 0
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Hey+it+just+started+to+rain+just+now
      media_content_type: provider
    metadata:
      title: Hey it just started to rain just now
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Hey+it+just+started+to+rain+just+now
  - service: notify.mobile_app_iphone
    data:
      message: Hey it has just started raining!
      title: Alert from Home Assistant
  mode: single
- id: '1660505820459'
  alias: VoIP Phone Offline
  description: If presence lost from router notify it is offline
  trigger:
  - platform: state
    entity_id:
    - device_tracker.voip_phone
  condition:
  - condition: template
    value_template: '{{ (now() - state_attr(''device_tracker.voip_phone'', ''last_activity'')
      | as_local > timedelta(minutes=10)) }}'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Hey+the+voice+over+IP+phone+has+gone+offline
      media_content_type: provider
    metadata:
      title: Hey the voice over IP phone has gone offline
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Hey+the+voice+over+IP+phone+has+gone+offline
  - service: notify.mobile_app_danies_iphone
    data:
      message: Hey the VoIP phone has gone offline. Check it's battery.
      title: Alert from Home Assistant
  mode: single
- id: '1660744900739'
  alias: Victron Modbus Write min SOC manual
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_number.multiplus_minimum_soc
  condition: []
  action:
  - service: modbus.write_register
    data_template:
      address: 2901
      slave: 100
      hub: victron
      value: '{{ states(''input_number.multiplus_minimum_soc'')|int * 10}}'
  mode: single
- id: '1660829853910'
  alias: Set slider from minimum SoC
  description: Sets slider to actual minimum SoC
  trigger:
  - platform: state
    entity_id:
    - sensor.victron_battery_min_soc
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.multiplus_minimum_soc
      value: '{{ states(''sensor.victron_battery_min_soc'')|int }}'
  mode: single
- id: '1661195626346'
  alias: Goodwood DRM's APRS beacon is offline
  description: Sent alert notification if tracker state changes to 'Away' for longer
    than 31 minutes (it beacons every 15 minutes). As it does not leave the zone and
    beacon a different GPS location, it never actually triggers the 'left zone' trigger.
  trigger:
  - platform: state
    entity_id:
    - device_tracker.zs1dcc_1
    to: not_home
    for:
      hours: 0
      minutes: 31
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone
    data:
      message: Goodwood ZS1DCC beacon is offline fro 30 minutes!
      title: Alert from Home Assistant
  mode: single
- id: '1661197173507'
  alias: Danie leaves his Mom
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.danies_iphone_3
    zone: zone.brown_annie_lawrence_home
    event: leave
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Hey%2C+Danie+has+just+left+his+mom+now
      media_content_type: provider
    metadata:
      title: Hey, Danie has just left his mom now
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Hey%2C+Danie+has+just+left+his+mom+now
  mode: single
- id: '1661198337205'
  alias: Shower hot water ready
  description: Trigger if grid power exceeds 1,500W for 20 minutes. Any other device
    is used less than 5 mins, and stove is usually running on solar or battery power.
    Then when usage dropped to below 1100W for at least a minute, trigger action to
    say water ready, but only if after 8am and before 11pm.
  trigger:
  - platform: numeric_state
    entity_id: sensor.power_usage_696087
    for:
      hours: 0
      minutes: 20
      seconds: 0
    above: '1500'
  condition:
  - condition: time
    after: 08:00:00
    before: '23:00:00'
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  action:
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.power_usage_696087
      for:
        hours: 0
        minutes: 1
        seconds: 0
      below: '1100'
    continue_on_timeout: false
  - service: notify.mobile_app_iphone
    data:
      message: Shower hot water should be ready!
      title: Alert from Home Assistant
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Shower+hot+water+should+be+ready+now%21
      media_content_type: provider
    metadata:
      title: Shower hot water should be ready now!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Shower+hot+water+should+be+ready+now%21
  mode: single
- id: '1661610916620'
  alias: Victron AC Overload Alarm
  description: 'Notification if AC overload alarm is triggered any time '
  trigger:
  - platform: state
    entity_id:
    - sensor.overload_alarm
    to: '2'
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Caution+an+alarm+has+been+triggered%21+You+are+using+too+much+power+off+the+inverter%21
      media_content_type: provider
    metadata:
      title: Caution an alarm has been triggered! You are using too much power off
        the inverter!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Caution+an+alarm+has+been+triggered%21+You+are+using+too+much+power+off+the+inverter%21
  mode: single
- id: '1661611188926'
  alias: Grid Lost Notification
  description: Notify if grid power lost during normal daily usage hours. Input source
    240 = unavailable grid, whilst 1 is grid available
  trigger:
  - platform: state
    entity_id:
    - sensor.active_input_source
    to: '240'
    for:
      hours: 0
      minutes: 0
      seconds: 15
    from: '1'
  condition:
  - condition: time
    after: 08:30:00
    before: '23:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=The+grid+power+has+just+been+lost...+use+power+sparingly+please
      media_content_type: provider
    metadata:
      title: The grid power has just been lost... use power sparingly please
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=The+grid+power+has+just+been+lost...+use+power+sparingly+please
  mode: single
- id: '1661611664417'
  alias: Warn of high AC load
  description: Audible warning if power usage approaching 5 kW inverter average load
    limit. Let amount exceed for 15 seconds as peaks can be higher for short periods.
  trigger:
  - platform: numeric_state
    entity_id: sensor.ac_loads
    for:
      hours: 0
      minutes: 0
      seconds: 15
    above: '4700'
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.lounge_speaker
    data:
      media_content_id: media-source://tts/google_translate?message=Warning%21+Power+usage+approaching+inverter+limit.+Check+Victron+display+on+kitchen+wall.
      media_content_type: provider
    metadata:
      title: Warning! Power usage approaching inverter limit. Check Victron display
        on kitchen wall.
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Warning%21+Power+usage+approaching+inverter+limit.+Check+Victron+display+on+kitchen+wall.
  - service: notify.mobile_app_iphone
    data:
      message: AC load on inverter approaching limit!
      title: Alert from Home Assistant
  mode: single
