# Loads default set of integrations. Do not remove.
default_config:

# Allows local Nginx Proxy Manager
# 2FA enabled already too
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# Load Ambient weather station API data
ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key

# APRS tracker devices
device_tracker:
  - platform: aprs
    username: ZS1OSS  # or FO0BAR-1 to FO0BAR-15
    callsigns:
      - 'ZS1OSS*'
      - 'ZS1DCC-1'

# Enable backups
backup:

modbus: !include modbus.yaml
#monitor_docker: !include monitor_docker.yaml

# Load OurGroceries app API
#ourgroceries:
#  username: !secret our_groceries_username
#  password: !secret our_groceries_password
  

# Uncomment below to generate debug logging
logger:
  default: warning
  # default: critical
  #logs:
    # Modbus debug lines
    #homeassistant.components.modbus: debug
    #pymodbus: debug
    # Glances debug lines
    #homeassistant.components.glances: debug
    #glances_api: debug
    #aiohttp: debug
